name: CreatingRhythms
version: !include "./VERSION"
description: |-
  An implementation of the algorithms from
  [Creating Rhythms](https://abrazol.com/books/rhythm1/) by Stefan Hollos and
  J. Richard Hollos.
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/creating-rhythms
language: GHC2021
extra-source-files:
  - VERSION
data-files:
  examples/*.bdf
dependencies:
  - base
ghc-options:
  - -Wall
  - -Werror
library:
  default-extensions:
    - StrictData
  ghc-options:
    - -fwarn-incomplete-patterns
  source-dirs: src
  dependencies:
    - combinat
    - containers
    - control-bool
    - extra
    - fast-digits
    - finite-typelits
    - lens
    - monad-loops
    - mtl
    - random
    - recursion-schemes
    - slist
    - trifecta
    - vector
    - vector-sized
benchmarks:
  bench:
    ghc-options: -threaded -with-rtsopts=-N -O2
    main: Benchmark.hs
    source-dirs: bench
    dependencies:
      - CreatingRhythms
      - criterion
_executable: &executable
  dependencies:
    - CreatingRhythms
    - optparse-applicative
  ghc-prof-options:
    - -fprof-auto
    - -rtsopts
  source-dirs: app
executables:
  b2int:
    <<: *executable
    main: b2int/Main.hs
  bdrum:
    <<: *executable
    dependencies:
      - CreatingRhythms
      - optparse-applicative
      - trifecta
    main: bdrum/Main.hs
  cfcv:
    <<: *executable
    main: cfcv/Main.hs
  cfsqrt:
    <<: *executable
    main: cfsqrt/Main.hs
  chsequl:
    <<: *executable
    main: chsequl/Main.hs
  comp:
    <<: *executable
    main: comp/Main.hs
  compa:
    <<: *executable
    main: compa/Main.hs
  compam:
    <<: *executable
    main: compam/Main.hs
  compm:
    <<: *executable
    main: compm/Main.hs
  compmrnd:
    <<: *executable
    main: compmrnd/Main.hs
  comprnd:
    <<: *executable
    main: comprnd/Main.hs
  debruijn:
    <<: *executable
    main: debruijn/Main.hs
    dependencies:
      - CreatingRhythms
      - finite-typelits
      - optparse-applicative
  int2b:
    <<: *executable
    main: int2b/Main.hs
  markovgen:
    <<: *executable
    main: markovgen/Main.hs
    dependencies:
      - CreatingRhythms
      - optparse-applicative
      - trifecta
  neck:
    <<: *executable
    main: neck/Main.hs
    dependencies:
      - CreatingRhythms
      - finite-typelits
      - optparse-applicative
  necka:
    <<: *executable
    main: necka/Main.hs
    dependencies:
      - CreatingRhythms
      - finite-typelits
      - optparse-applicative
  neckam:
    <<: *executable
    main: neckam/Main.hs
    dependencies:
      - CreatingRhythms
      - finite-typelits
      - optparse-applicative
  neckm:
    <<: *executable
    main: neckm/Main.hs
    dependencies:
      - CreatingRhythms
      - finite-typelits
      - optparse-applicative
  part:
    <<: *executable
    main: part/Main.hs
    dependencies:
      - CreatingRhythms
      - combinat
      - optparse-applicative
  parta:
    <<: *executable
    main: parta/Main.hs
    dependencies:
      - CreatingRhythms
      - combinat
      - optparse-applicative
  partam:
    <<: *executable
    main: partam/Main.hs
    dependencies:
      - CreatingRhythms
      - combinat
      - optparse-applicative
  partm:
    <<: *executable
    main: partm/Main.hs
    dependencies:
      - CreatingRhythms
      - combinat
      - optparse-applicative
  permi:
    <<: *executable
    main: permi/Main.hs
  pfold:
    <<: *executable
    main: pfold/Main.hs
    dependencies:
      - CreatingRhythms
      - extra
      - optparse-applicative
  rndint:
    <<: *executable
    main: rndint/Main.hs
    dependencies:
      - CreatingRhythms
      - finite-typelits
      - optparse-applicative
tests:
  unit:
    build-tools:
      - tasty-discover
    dependencies:
      - CreatingRhythms
      - tasty
      - tasty-discover
      - tasty-hunit
    main: Main.hs
    source-dirs: test
