name: Publish docs

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Nix
        uses: cachix/install-nix-action@v31
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Configure Cachix
        uses: cachix/cachix-action@v16
        with:
          name: yurrriq
          skipPush: true
      - id: pages
        name: Configure Pages
        uses: actions/configure-pages@v5
      - name: Build docs
        run: |
          nix build .#creating-rhythms.doc --no-link --print-out-paths |
              xargs -I% find % -name html |
              xargs -I% cp -r % _site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GiHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
